name: ml_smile
description: Showcasing Google ML Kit

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.4+20
  confetti: ^0.6.0
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  google_ml_kit: ^0.8.0
  logger: ^1.1.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
